version: '3'
services:
  web:
    ports:
    - target: 8081
      published: 0
      protocol: tcp
    - target: 5005
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/web/Dockerfile
