services:
  web:
    depends_on:
    - mysql
    ports:
    - target: 80
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=drupal
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
